<div class="info">	
	<div class="conteudo-admin">
	<h2>Gerenciar Ingredientes</h2>
	<div class="forms-admin">
		
		<p><a href="<?PHP echo $this->url(array('action' => 'adicionar')); ?>">ADICIONAR NOVO INGREDIENTE</a> 
		<table border="1" width="98%">
			<tr class="linha3">
				<th>Nome</th>
				<th align="center">Relacionar</th>
				<th align="center">Editar</th>
				<th align="center">Remover</th>
			</tr>
			<?php $linha = 0;?>
		<?PHP foreach ($this->ingrediente as $produto): ?>
			<?php 
			if($linha == 0){
				echo '<tr class="linha1">';
				$linha = 1;
			}else{
				echo '<tr class="linha2">';
				$linha = 0;
			}
			?>
				<td><?PHP echo $produto['nome_ingrediente']; ?></td>
				<td align="center"><a href="<?PHP echo $this->url(array('controller' => 'relacionamentos','action' => 'index', 'id' => $produto['id_ingrediente'])); ?>">Relacionar ingrediente a produto</a></td>
				<td align="center"><a href="<?PHP echo $this->url(array('action' => 'editar', 'id' => $produto['id_ingrediente'])); ?>">Editar</a></td>
				<td align="center"><a href="<?PHP echo $this->url(array('action' => 'remover', 'id' => $produto['id_ingrediente'])); ?>">Excluir</a></td>
			</tr>
		<?PHP endforeach; ?>
		</table>
			<input type="button" value=" Voltar " onclick="history.go(-1)">	
		</div>
	
	</div>
	
		
</div>
