<div class="info">	
	<div class="conteudo-admin">
	<h2>Gerenciar Combos</h2>
	<div class="forms-admin">
		
		<a href="<?PHP echo $this->url(array('action' => 'adicionar')); ?>">ADICIONAR NOVO COMBO</a> 
		<table border="1" width="98%">
			<tr class="linha3">
				<th>ID</th>
				<th>Produto 1</th>
				<th>Produto 2</th>
				<th>Produto 3</th>
				<th>Produto 4</th>
				<th>Produto 5</th>
				<th>Preço</th>
				<th align="center">Editar</th>
				<th align="center">Remover</th>
			</tr>
		<?php $linha = 0;?>
		<?PHP foreach ($this->combo as $combo): ?>
			<?php 
			$id = array($combo['id_produto1'],$combo['id_produto2'],$combo['id_produto3'],$combo['id_produto4'],$combo['id_produto5']);
			
			$produtoModel = new Application_Model_Produto();

			for($i = 0;$i < 5;$i++){
				if($id[$i] != null){
					$idx = $id[$i];
					$produto[$i] = $produtoModel->fetchAll(
											$produtoModel->select()
											->from($produtoModel->info(Zend_Db_Table_Abstract::NAME))
											->columns(array('nome'))
											->where('id_produto LIKE :idx')
												->bind(array(
													'idx' => '%' . $idx . '%'
												))

					);
				}else{ $produto[$i][0]['nome'] = 'nenhum';}
			}
			?>
			<?php 
			if($linha == 0){
				echo '<tr class="linha1">';
				$linha = 1;
			}else{
				echo '<tr class="linha2">';
				$linha = 0;
			}
			?>
				<td><?PHP echo $combo['id_combo']; ?></td>
				<td><?PHP echo $produto[0][0]['nome']; ?></td>
				<td><?PHP echo $produto[1][0]['nome']; ?></td>
				<td><?PHP echo $produto[2][0]['nome']; ?></td>
				<td><?PHP echo $produto[3][0]['nome']; ?></td>
				<td><?PHP echo $produto[4][0]['nome']; ?></td>
				<td><?PHP echo 'R$ ' . number_format($combo['preco'] / 100, 2, ',', '.'); ?></td>
				<td align="center"><a href="<?PHP echo $this->url(array('action' => 'editar', 'id' => $combo['id_combo'])); ?>">Editar</a></td>
				<td align="center"><a href="<?PHP echo $this->url(array('action' => 'remover', 'id' => $combo['id_combo'])); ?>">Excluir</a></td>
			</tr>
		<?PHP endforeach; ?>
		</table>
			<input type="button" value=" Voltar " onclick="history.go(-1)">	
		</div>
	
	</div>
	
		
</div>
