<div class="info-cardapio">	
	<div class="menu-left">
			<h2>Categorias</h2>
				<ul>
		<?php if(isset($this->categorias)):?>
							<?PHP foreach ($this->categorias as $categoria): ?>
							<li><a href="<?PHP echo $this->url(array('module' => 'default', 'controller' => 'cardapio', 'action' => 'index', 'categoria' => $categoria['nome_categoria']), null, true); ?>"><?php echo $categoria['nome_categoria'];?></a></li>
							<?PHP endforeach; ?>
		<?php else:?>
					<li>Categoria 1</li>
					<li>Categoria 2</li>
					<li>Categoria 3</li>
					<li>Categoria 4</li>
					<li>Categoria 5</li>
					<li>Categoria 6</li>
					<li>Categoria 7</li>
					<li>Categoria 8</li>
		<?php endif;?>
				</ul>
		</div>
	
	<div class="conteudo">
	<?php if(isset($this->cat)):?>
			<h2><?php echo $this->cat;?></h2>
		<?php else:?>
			<h2>Todos os produtos</h2>
	<?php endif;?>
	<?php if(isset($this->cat) && $this->cat == 'Combos'):?>
		<?PHP foreach ($this->produto as $produto): ?>
			<h4>Produto 1: <?php echo $produto['id_produto1'];?>
			Produto 2: <?php echo $produto['id_produto2'];?>
			Produto 3: <?php echo $produto['id_produto3'];?>
			Produto 4: <?php echo $produto['id_produto4'];?>
			Produto 5: <?php echo $produto['id_produto5'];?>
			Preço: <?php echo $produto['preco'];?></h4>
		<?PHP endforeach; ?>
	<?php else:?>
		<?PHP foreach ($this->produto as $produto): ?>
				<div class="product">
					<img width="100" height="100" src="<?php echo 'http://' . $_SERVER['HTTP_HOST'] . '/img/produtos/'. $produto['id_produto'] . '.jpg'; ?>"/>
								<small><a href="<?PHP echo $this->url(array('module' => 'default', 'controller' => 'cardapio', 'action' => 'adicionar', 'id' => $produto['id_produto']), null, true); ?>">Adicionar ao carrinho</a></small><br />

				</div>
		<?PHP endforeach; ?>
	<?php endif;?>
	</div>


	    
</div>	