<div class="info">	
	<div class="conteudo-admin">
	<h2>Gerenciar Produtos</h2>
	<div class="forms-admin">
		
		<a href="<?PHP echo $this->url(array('action' => 'adicionar')); ?>">ADICIONAR NOVO PRODUTO</a> 
		<table border="1" width="98%">
			<tr class="linha3">
				<th>Imagem</th>
				<th>Nome</th>
				<th>Descrição</th>
				<th>Preço</th>
				<th>Categoria</th>
				<th>Promoção?</th>
				<th align="center">Editar</th>
				<th align="center">Remover</th>
			</tr>
			<?php $linha = 0;?>
		<?PHP foreach ($this->produto as $produto): ?>
			<?php 
			if($linha == 0){
				echo '<tr class="linha1">';
				$linha = 1;
			}else{
				echo '<tr class="linha2">';
				$linha = 0;
			}
			?>
                <td align="center"><img width="100" height="100" src=<?php echo 'http://' . $_SERVER['HTTP_HOST'] . '/img/produtos/'. $produto['id_produto'] . '.jpg'; ?> alt="<?PHP echo $produto['nome']; ?>" title="<?PHP echo $produto['nome']; ?>" /></td>
				<td><?PHP echo $produto['nome']; ?></td>
				<td><?PHP echo $produto['descricao']; ?></td>
				<td><?PHP echo 'R$ ' . number_format($produto['preco'] / 100, 2, ',', '.'); ?></td>
				<td><?PHP echo $produto['categoria']; ?></td>
				<td><?PHP if($produto['promocao'] == 1){echo 'sim';}else{echo 'não';} ?></td>
				<td align="center"><a href="<?PHP echo $this->url(array('action' => 'editar', 'id' => $produto['id_produto'])); ?>">Editar</a></td>
				<td align="center"><a href="<?PHP echo $this->url(array('action' => 'remover', 'id' => $produto['id_produto'])); ?>">Excluir</a></td>
			</tr>
		<?PHP endforeach; ?>
		</table>
			<input type="button" value=" Voltar " onclick="history.go(-1)">	
		</div>
	
	</div>
	
		
</div>
