<?PHP
Zend_Loader::loadClass('Zend_Auth');
$authClass = Zend_Auth::getInstance();

if ($authClass->hasIdentity()) {
    $auth = $authClass->getStorage()->read();

    $id = $auth['usuario_id'];

    $usuarioModel = new Application_Model_Usuario();

    $usuario = $usuarioModel->find($id)->current();
}
?>


<div class="info">	
	<div class="conteudo">
		<h2>Cadastro de usuário - Contato</h2>
	<?PHP echo $this->form; ?>
	* Indica campo obrigatório
	</div>
</div>	