<div class="info">	
	<div class="conteudo-admin">
		<h2>Categorias</h2>
		<div class="forms-admin">
			<a href="<?PHP echo $this->url(array('action' => 'adicionar')); ?>">Adicionar categoria</a>
			<table border="1" width="98%">
				<tr class="linha3">

					<th>Id</th>
					<th>Nome</th>
					<th align="center">Editar</th>
					<th align="center">Remover</th>
				</tr>
			<?php $linha = 0;?>
			<?PHP foreach ($this->categoria as $categoria): ?>
			<?php 
			if($linha == 0){
				echo '<tr class="linha1">';
				$linha = 1;
			}else{
				echo '<tr class="linha2">';
				$linha = 0;
			}
			?>
			<td><?PHP echo $categoria['id_categoria']; ?></td>
					<td><?PHP echo $categoria['nome_categoria']; ?></td>
					<td align="center"><a href="<?PHP echo $this->url(array('action' => 'editar', 'id' => $categoria['id_categoria'])); ?>">X</a></td>
					<td align="center"><a href="<?PHP echo $this->url(array('action' => 'remover', 'id' => $categoria['id_categoria'])); ?>">X</a></td>
				</tr>
			<?PHP endforeach; ?>
			
			</table>
			<input type="button" value=" Voltar " onclick="history.go(-1)">	
		</div>
	</div>
</div>